name: indian_pincode_validator
description: A simple Dart/Flutter package to validate Indian pinCodes and fetch city/state using the public postal API.
version: 1.0.0
homepage: https://github.com/DivyaYadavareddy/indian_pincode_validator/tree/main
repository: https://github.com/DivyaYadavareddy/indian_pincode_validator/tree/main


environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
